### PR TITLE
Fix cell height issue

### LINKED ISSUE #655: Cell height issue on searched tables
screen shot 2015-03-31 at 3 58 15 pm

```ruby
class EditTrainersScreen < PM::TableScreen

  title "Custom Trainers"
  row_height :auto, estimated: 65.5
  searchable placeholder: "Search trainers"

  # ...
end
```

### PR DESCRIPTION
**Pull request by jamonholmgren**
Attempt number 3. Fixes #655. @markrickert @kevinvangelder @ryanlntn .

### CODE REVIEW

**Comment by jamonholmgren** [comment]
Travis...

File: lib/ProMotion/table/table.rb [hunk 1]
```diff
@@ -172,42 +172,43 @@ def edit_mode?
...
+    def tableView(_, willDisplayCell: table_cell, forRowAtIndexPath: index_path)
       data_cell = self.promotion_table_data.cell(index_path: index_path)
       table_cell.send(:will_display) if table_cell.respond_to?(:will_display)
       table_cell.send(:restyle!) if table_cell.respond_to?(:restyle!) # Teacup compatibility
     end
 
-    def tableView(table_view, heightForRowAtIndexPath: index_path)
-      (self.promotion_table_data.cell(index_path: index_path)[:height] || table_view.rowHeight).to_f
+    def tableView(_, heightForRowAtIndexPath: index_path)
+      # mp "table: #{table_view.rowHeight} cell: #{self.promotion_table_data.cell(index_path: index_path)[:height].inspect}"
```
Comment (markrickert) [inline lib/ProMotion/table/table.rb]: Remove this commented out print statement?

**Comment by markrickert** [comment]
I'm not seeing what you actually fixed here... it looks like just a code cleanup with var name changes and two-liners -> one-liners.

File: lib/ProMotion/table/table.rb [hunk 2]
```diff
@@ -172,42 +172,43 @@ def edit_mode?
...
+      (self.promotion_table_data.cell(index_path: index_path)[:height] || tableView.rowHeight).to_f
```
Comment (jamonholmgren) [inline lib/ProMotion/table/table.rb]: @markrickert The relevant change is that I'm referencing the built-in `tableView` property rather than the passed-in `table_view` var. The search creates another UITableView on top of our table view, which is problematic in that it doesn't contain the settings (`rowHeight` in this case) that we need. I removed the local reference so we aren't tempted to use it.

This will all get re-written anyway when we update for iOS 8's new table searchable stuff. But it does work for now.

Comment (markrickert) [inline lib/ProMotion/table/table.rb]: AHA! I see it now. Good catch.
